server:
  port: 8082
  servlet:
    context-path: /itactive

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/itActivities
    driver-class-name: org.postgresql.Driver
    username: root
    password: 123
  jpa:
    database: postgresql
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath*:database/initDB.sql
      data-locations: classpath*:database/populateDB.sql


integrations:
  user-service:
    url: http://localhost:8085/user/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000