server:
  port: 8083
  servlet:
    context-path: /jobs

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobs
    driver-class-name: org.postgresql.Driver
    username: root
    password: 123
  jpa:
    database: postgresql
    show-sql: true
  sql:
    init:
      mode: always
#      schema-locations: classpath*:database/initDB.sql
#      data-locations: classpath*:database/populateDB.sql


integrations:
  department-service:
    url: http://localhost:8081/departments/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000